# -*- mode: python -*-
Import("env")

env = env.Clone()

env.CppUnitTest(
    target="oidc_test",
    source=[
        "oidc_commands_test.cpp",
        "oidc_identity_providers_registry_test.cpp",
        "user_request_oidc_test.cpp"
    ],
    LIBDEPS=[
        "$BUILD_DIR/mongo/crypto/jwt",
        "$BUILD_DIR/mongo/db/audit",
        "$BUILD_DIR/mongo/db/auth/auth_impl_internal",
        "$BUILD_DIR/mongo/db/auth/authmocks",
        "$BUILD_DIR/mongo/db/auth/authorization_session_test_fixture",
        "oidc",
        "oidc_commands",
    ],
)
