# -*- mode: python -*-
Import("env")

env = env.Clone()

env.Library(
    target='oidc_server_parameters',
    source=[
        'oidc_server_parameters.cpp',
        'oidc_server_parameters.idl',
        'oidc_server_parameters_logger.cpp',
    ],
    LIBDEPS=[
        '$BUILD_DIR/mongo/base',
        '$BUILD_DIR/mongo/db/server_base',
        '$BUILD_DIR/mongo/util/options_parser/options_parser',
    ],
)
