# -*- mode: python -*-
Import("env")

env = env.Clone()

env.CppUnitTest(
    target="db_encryption_key_id_test",
    source=[],
)

env.CppUnitTest(
    target="vault_secret_metadata_locator_test",
    source=[],
)

env.CppUnitTest(
    target="encryption_status_test",
    source=[],
)

env.CppUnitTest(
    target='vault_client_test',
    source=[],
)
