# -*- mode: python -*-

Import([
    'env',
    'has_feature_option',
])

env = env.Clone()

env.SConscript(
    dirs=[
        'external',
    ],
    exports=[
        'env',
    ],
)

if has_feature_option('enable-oidc'):
    env.SConscript(
        dirs=[
            'oidc',
        ],
        exports=[
            'env',
        ],
    )

env = env.Clone()
env.CppUnitTest(
    target="db_auth_test",
    source=[],
    LIBDEPS=[],
)
