# -*- mode: python -*-
Import(
    [
        "env",
        "has_option",
        "wiredtiger",
    ]
)

if not wiredtiger:
    Return()

env = env.Clone()

env.CppUnitTest(
    target="storage_wiredtiger_encryption_test",
    source=[],
)

env.CppUnitTest(
    target="storage_wiredtiger_kv_engine_encryption_key_test",
    source=[],
)

env.CppUnitTest(
    target="storage_wiredtiger_test",
    source=[],
)

env.CppUnitTest(
    target="storage_wiredtiger_record_store_and_index_test",
    source=[],
)

env.Benchmark(
    target="storage_wiredtiger_record_store_and_index_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="storage_bm",
)

env.Benchmark(
    target="storage_wiredtiger_begin_transaction_block_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="storage_bm",
)

env.Benchmark(
    target="write_conflict_retry_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="storage_bm",
)
