Import("env")
Import("inmemory")

env = env.Clone()

if inmemory:
    imEnv = env.Clone()
    imEnv.InjectThirdParty(libraries=["wiredtiger"])
    imEnv.InjectThirdParty(libraries=["zlib"])
    imEnv.InjectThirdParty(libraries=["valgrind"])

    imEnv.CppUnitTest(
        target="storage_inmemory_init_test",
        source=[],
    )

    imEnv.CppUnitTest(
        target="storage_inmemory_kv_engine_test",
        source=[],
    )
