# -*- mode: python -*-

Import(
    [
        "env",
        "has_option",
    ]
)

env = env.Clone()

env.Benchmark(
    target="op_observer_bm",
    source=[],
    LIBDEPS=[],
)

env.CppUnitTest(
    target="db_op_observer_test",
    source=[],
    LIBDEPS=[],
)
