# -*- mode: python -*-

Import(
    [
        "env",
        "has_option",
    ]
)

env = env.Clone()

env.SConscript(
    must_exist=1,
    dirs=[
        "inmemory",
        "key_string",
        "wiredtiger",
    ],
    exports=[
        "env",
    ],
)

env.Benchmark(
    target="storage_record_id_bm",
    source=[],
    BAZEL_BENCHMARK_TAG="first_half_bm",
)

env.CppUnitTest(
    target="db_storage_test",
    source=[],
)
