# -*- mode: python -*-

Import(
    [
        "env",
        "has_option",
    ]
)

env = env.Clone()

env.SConscript(
    must_exist=1,
    dirs=[
        "exec",
        "planner",
    ],
    exports=[
        "env",
    ],
)
