name: build

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

permissions:
  contents: read
  security-events: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Fetch upstream tags
        run: |
          git remote add upstream https://github.com/mongodb/mongo.git || true
          git fetch upstream --tags

      # - name: Setup AWS SDK
      #   uses: ./.github/actions/setup-aws-sdk

      - name: Bazel cache
        uses: actions/cache@v4
        id: bazel_cache
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazelisk
          key: ${{ runner.os }}-bazel-cache

      - name: Configure bazel
        run: |
          {
            echo 'common --//bazel/config:build_enterprise=False'
            echo 'build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}'
          } > .bazelrc.local

      - name: Build
        run: |
          bazel build \
            --jobs=200 \
            --config=psmdb_dev \
            --config=bb \
            --announce_rc \
            --show_result=0 \
            --build_event_text_file=/dev/stdout \
            --verbose_failures \
            //:install-devcore
