name: mergai-on-push

on:
  push:
    branches:
      - 'mergai/*/baseline'


jobs:
  merge-job:
    environment: restricted
    runs-on: ubuntu-latest

    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MergAI
        uses: ./.github/actions/setup-mergai
        with:
          token: ${{ secrets.PAT }}

      - name: Fetch notes
        shell: bash
        run: |
          git fetch origin '+refs/notes/*:refs/notes/*'

      - name: MergAI log
        shell: bash
        run: |
          mergai log
