# .github/workflows/mock-workflow.yml
name: mergai-trigger

on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'Commit SHA to run the workflow against'
        required: false
        default: '9e6366f4b79'
      gemini-model:
        description: 'Gemini model to use for conflict resolution'
        required: false
        default: 'gemini-2.5-flash'
      mergai-ref:
        description: 'MergAI git reference to checkout'
        required: false
        default: 'main'

jobs:
  mergai-trigger:
    environment: restricted
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.PAT }}
      GOOGLE_CLOUD_PROJECT: ${{ secrets.GOOGLE_CLOUD_PROJECT}}
      GOOGLE_CLOUD_LOCATION: ${{ secrets.GOOGLE_CLOUD_LOCATION}}
      GOOGLE_GENAI_USE_VERTEXAI: "true"

    steps:

      - name: Write GCP credentials
        run: |
          echo '${{ secrets.GCP_CREDENTIALS }}' | base64 -d > $RUNNER_TEMP/gcp-key.json
          chmod 600 $RUNNER_TEMP/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$RUNNER_TEMP/gcp-key.json" >> $GITHUB_ENV

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # or whatever you use locally

      - name: Install gemini-cli
        run: |
          npm install -g @google/gemini-cli

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # needed to access all branches and commits

      - name: Git config
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config merge.conflictstyle diff3
          git config notes.displayRef refs/notes/mergai-marker

      - name: Fetch notes
        run: |
          git fetch origin refs/notes/mergai-marker:refs/notes/mergai-marker
          git fetch origin refs/notes/mergai:refs/notes/mergai

      - name: Fetch upstream
        run: |
          git remote add upstream https://github.com/mongodb/mongo.git
          git fetch upstream

      - name: Verify input commit is valid
        run: |
          if ! git cat-file -e ${{ inputs.commit }}^{commit}; then
            echo "Error: Commit ${{ inputs.commit }} does not exist."
            exit 1
          fi

      - name: Setup MergAI
        uses: ./.github/actions/setup-mergai
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ inputs.mergai-ref }}

      - name: Define base branch name
        run: |
          REF=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          echo "BASE_BRANCH_NAME=${REF}" >> $GITHUB_ENV
          echo "BASELINE_BRANCH=mergai/merging-${{ inputs.commit }}-into-${REF}/baseline" >> $GITHUB_ENV
          echo "SOLUTION_BRANCH=mergai/merging-${{ inputs.commit }}-into-${REF}/solution" >> $GITHUB_ENV

      - name: Show input parameters
        run: |
          echo "Executing merging workflow:"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ inputs.commit }}"

      - name: "Creating baseline branch"
        run: |
          git checkout -b $BASELINE_BRANCH
          git push -f origin $BASELINE_BRANCH


      - name: Merge commit
        continue-on-error: true
        run: |
          git merge --no-ff ${{ inputs.commit }}

      - name: Show status
        run: |
          git status

      - name: mergai create-conflict-context
        shell: bash
        run: |
          mergai create-conflict-context
          mergai status

      - name: mergai commit-conflict
        shell: bash
        run: |
          mergai commit-conflict
          git show

      - name: mergai prompt
        shell: bash
        run: |
          mergai prompt

      - name: create solution branch
        run: |
          git checkout -b $SOLUTION_BRANCH

      - name: mergai resolve
        shell: bash
        run: |
          mergai resolve -y
          git status
          mergai status

      - name: mergai commit-resolution
        shell: bash
        run: |
          mergai commit
          git show

      - name: Create pull request
        shell: bash
        run: |
          git push -f origin $BASELINE_BRANCH
          git push -f origin $SOLUTION_BRANCH
          git push origin refs/notes/mergai-marker
          git push origin refs/notes/mergai
          mergai pr --repo $GITHUB_REPOSITORY create --base $BASELINE_BRANCH


